spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: library-event
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      max.block.ms: 10000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        
server:
   port: 8080        